In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('C:\Machine Learning\Machine Learning A-Z Template Folder\Part 8 - Deep Learning\Section 39 - Artificial Neural Networks (ANN)\Artificial_Neural_Networks\Churn_Modelling.csv')

In [3]:
dataset.head(2)


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [4]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [14]:
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,13].values

In [15]:
x[:,1]

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

In [16]:
from sklearn.preprocessing import LabelEncoder
lb1 = LabelEncoder()
x[:,1] = lb1.fit_transform(x[:,1])

In [22]:
lb2 = LabelEncoder()
x[:,2] = lb1.fit_transform(x[:,2])

In [23]:
from sklearn.preprocessing import OneHotEncoder
o1 = OneHotEncoder(categorical_features = [1])
x = o1.fit_transform(x).toarray()


In [26]:
x=x[:,1:]

In [27]:
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.3,random_state = 0)

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [28]:
import keras
from keras.models import Sequential
from keras.layers import Dense

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [29]:
model=Sequential()

In [32]:
x_train.shape

(7000, 11)

In [33]:
model.add(Dense(input_dim=11,init="random_uniform",activation='relu',output_dim=6))

Instructions for updating:
Colocations handled automatically by placer.


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, activation="relu", units=6, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [34]:
model.add(Dense(init="random_uniform",activation='relu',output_dim=6))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [35]:
model.add(Dense(output_dim=1,init='random_uniform',activation='sigmoid'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [37]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [41]:
model.fit(x_train,y_train,epochs=50,batch_size=32)

Epoch 1/50
7000/7000 [==============================] - 0s 56us/step - loss: 0.4973 - acc: 0.7977
Epoch 2/50
7000/7000 [==============================] - 0s 54us/step - loss: 0.4398 - acc: 0.8136
Epoch 3/50
7000/7000 [==============================] - 0s 58us/step - loss: 0.4058 - acc: 0.8293
Epoch 4/50
7000/7000 [==============================] - 0s 54us/step - loss: 0.3916 - acc: 0.8343
Epoch 5/50
7000/7000 [==============================] - 0s 54us/step - loss: 0.3824 - acc: 0.8416
Epoch 6/50
7000/7000 [==============================] - 0s 55us/step - loss: 0.3757 - acc: 0.8481
Epoch 7/50
7000/7000 [==============================] - 0s 53us/step - loss: 0.3699 - acc: 0.8506
Epoch 8/50
7000/7000 [==============================] - 0s 56us/step - loss: 0.3654 - acc: 0.8533
Epoch 9/50
7000/7000 [==============================] - 0s 53us/step - loss: 0.3602 - acc: 0.8554
Epoch 10/50
7000/7000 [==============================] - 0s 54us/step - loss: 0.3567 - acc: 0.8587
Epoch 11/50
7000/70

In [51]:
y_pred=model.predict(x_test)

In [53]:
y_pred.min()

0.0024597943

In [44]:
y_pred = (y_pred > 0.5)

In [45]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [47]:
y_p=model.predict(np.array([[0,1,100,1,25,8,115000,24,1,1,100000]]))

In [48]:
y_p

array([[1.]], dtype=float32)

In [49]:
y_p = (y_p > 0.5)

In [50]:
y_p

array([[ True]])